apiVersion: v1
kind: Service
metadata:
  name: react
  labels:
    app: react
spec:
  type: LoadBalancer
  selector:
    app: react
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: us-central1-docker.pkg.dev/ml-deployment-app-370904/ml-deployment-repo/ml-deployment-react:v2
        imagePullPolicy: IfNotPresent
