# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\"\x1b\n\nmodelInput\x12\r\n\x01X\x18\x01 \x03(\x02\x42\x02\x10\x01\" \n\x0bmodelOutput\x12\x11\n\x05preds\x18\x01 \x03(\x02\x42\x02\x10\x01\x32\x31\n\x07predict\x12&\n\x07Predict\x12\x0b.modelInput\x1a\x0c.modelOutput\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELINPUT.fields_by_name['X']._options = None
  _MODELINPUT.fields_by_name['X']._serialized_options = b'\020\001'
  _MODELOUTPUT.fields_by_name['preds']._options = None
  _MODELOUTPUT.fields_by_name['preds']._serialized_options = b'\020\001'
  _MODELINPUT._serialized_start=17
  _MODELINPUT._serialized_end=44
  _MODELOUTPUT._serialized_start=46
  _MODELOUTPUT._serialized_end=78
  _PREDICT._serialized_start=80
  _PREDICT._serialized_end=129
# @@protoc_insertion_point(module_scope)
